### ISSUE TITLE
XGBoost failing on A2 machines but the same code works in L4 GPU

### ISSUE THREAD

**Issue by jjayadeep06** [dmlc/xgboost#11450]
When I run the below code on A2 machine:-
```
import random

from xgboost.spark import SparkXGBClassifier
from pyspark.sql import SparkSession
from pyspark.ml.feature import VectorAssembler

spark = SparkSession.builder \
        .appName("DistributedXGBoostGPUTraining") \
        .getOrCreate()

dataset_size = 100_000
labels = [0, 1, 2]

feature_cols = ["feature1", "feature2", "feature3"]
label_col = "label"
pred_col_name = "pred"
all_cols = ["id1", "id2"] + feature_cols + [label_col]

data = [
    (i+1, i+1001, random.random(), random.random() * 1_000, random.random() * 1_000, random.choice(labels))
    for i in range(dataset_size)
]

prediction_input = spark.createDataFrame(data, ("id1", "id2", "feature1", "feature2", "feature3", 'label'))

# VectorAssembler required if you cannot train on GPU
vec_assembler = VectorAssembler(inputCols=feature_cols, outputCol="features")
prediction_input = vec_assembler.transform(prediction_input)

prediction_input.show(5)

# create a xgboost pyspark regressor estimator and set device="cuda"
classifier = SparkXGBClassifier(
  features_col='features',
  device='cuda',
  label_col=label_col,
  num_workers=2
)

# train and return the model
model = classifier.fit(prediction_input)

# predict on test data
predict_df = model.transform(prediction_input)
predict_df.show(5)
spark.stop()
exit(0)
print("Called Stop")
```
I am getting the below error

```
  File "/opt/conda/default/lib/python3.11/site-packages/xgboost/core.py", line 284, in _check_call
    raise XGBoostError(py_str(_LIB.XGBGetLastError()))
xgboost.core.XGBoostError: [06:28:12] /home/conda/feedstock_root/build_artifacts/xgboost-split_1744329155408/work/src/tree/updater_gpu_hist.cu:861: Exception in gpu_hist: [06:28:12] /home/conda/feedstock_root/build_artifacts/xgboost-split_1744329155408/work/src/collective/result.cc:78: 
- [nccl_stub.cc:38|06:28:12]: NCCL failure: unhandled cuda error (run with NCCL_DEBUG=INFO for details).  CUDA error: 

Stack trace:
  [bt] (0) /opt/conda/default/lib/libxgboost.so(dmlc::LogMessageFatal::~LogMessageFatal()+0x6e) [0x74f1747cf3de]
  [bt] (1) /opt/conda/default/lib/libxgboost.so(xgboost::collective::SafeColl(xgboost::collective::Result const&)+0x6a) [0x74f17486eafa]
  [bt] (2) /opt/conda/default/lib/libxgboost.so(xgboost::common::SketchContainer::AllReduce(xgboost::Context const*, bool)+0x8b8) [0x74f174f2b968]
  [bt] (3) /opt/conda/default/lib/libxgboost.so(xgboost::common::SketchContainer::MakeCuts(xgboost::Context const*, xgboost::common::HistogramCuts*, bool)+0xc8) [0x74f174f2c818]
  [bt] (4) /opt/conda/default/lib/libxgboost.so(xgboost::common::DeviceSketchWithHessian(xgboost::Context const*, xgboost::DMatrix*, int, xgboost::common::Span<float const, 18446744073709551615ul>, unsigned long)+0x4a4) [0x74f174eb3124]
  [bt] (5) /opt/conda/default/lib/libxgboost.so(xgboost::EllpackPageImpl::EllpackPageImpl(xgboost::Context const*, xgboost::DMatrix*, xgboost::BatchParam const&)+0x638) [0x74f174f9d708]
  [bt] (6) /opt/conda/default/lib/libxgboost.so(xgboost::EllpackPage::EllpackPage(xgboost::Context const*, xgboost::DMatrix*, xgboost::BatchParam const&)+0x32) [0x74f174f9db72]
  [bt] (7) /opt/conda/default/lib/libxgboost.so(xgboost::data::SimpleDMatrix::GetEllpackBatches(xgboost::Context const*, xgboost::BatchParam const&)+0x63e) [0x74f174afdade]
  [bt] (8) /opt/conda/default/lib/libxgboost.so(xgboost::tree::NoSampling::Sample(xgboost::Context const*, xgboost::common::Span<xgboost::detail::GradientPairInternal<float>, 18446744073709551615ul>, xgboost::DMatrix*)+0x27) [0x74f1752ac607]



Stack trace:
  [bt] (0) /opt/conda/default/lib/libxgboost.so(dmlc::LogMessageFatal::~LogMessageFatal()+0x6e) [0x74f1747cf3de]
  [bt] (1) /opt/conda/default/lib/libxgboost.so(xgboost::tree::GPUHistMaker::Update(xgboost::tree::TrainParam const*, xgboost::linalg::Tensor<xgboost::detail::GradientPairInternal<float>, 2>*, xgboost::DMatrix*, xgboost::common::Span<xgboost::HostDeviceVector<int>, 18446744073709551615ul>, std::vector<xgboost::RegTree*, std::allocator<xgboost::RegTree*> > const&)+0x97e) [0x74f1752f41ae]
  [bt] (2) /opt/conda/default/lib/libxgboost.so(xgboost::gbm::GBTree::BoostNewTrees(xgboost::linalg::Tensor<xgboost::detail::GradientPairInternal<float>, 2>*, xgboost::DMatrix*, int, std::vector<xgboost::HostDeviceVector<int>, std::allocator<xgboost::HostDeviceVector<int> > >*, std::vector<std::unique_ptr<xgboost::RegTree, std::default_delete<xgboost::RegTree> >, std::allocator<std::unique_ptr<xgboost::RegTree, std::default_delete<xgboost::RegTree> > > >*)+0x13b8) [0x74f174b38a58]
  [bt] (3) /opt/conda/default/lib/libxgboost.so(xgboost::gbm::GBTree::DoBoost(xgboost::DMatrix*, xgboost::linalg::Tensor<xgboost::detail::GradientPairInternal<float>, 2>*, xgboost::PredictionCacheEntry*, xgboost::ObjFunction const*)+0x483) [0x74f174b39143]
  [bt] (4) /opt/conda/default/lib/libxgboost.so(xgboost::LearnerImpl::UpdateOneIter(int, std::shared_ptr<xgboost::DMatrix>)+0x31f) [0x74f174b85c1f]
  [bt] (5) /opt/conda/default/lib/libxgboost.so(XGBoosterUpdateOneIter+0x69) [0x74f1746e0119]
  [bt] (6) /opt/conda/default/lib/python3.11/lib-dynload/../../libffi.so.8(+0x6d8a) [0x74f1a67e8d8a]
  [bt] (7) /opt/conda/default/lib/python3.11/lib-dynload/../../libffi.so.8(+0x61cd) [0x74f1a67e81cd]
  [bt] (8) /opt/conda/default/lib/python3.11/lib-dynload/../../libffi.so.8(ffi_call+0xcd) [0x74f1a67e891d]
```

But when I run the same code on `L4` GPU it works fine. What can be the issue ?

**Comment by trivialfis** [comment]
> NCCL failure: unhandled cuda error (run with NCCL_DEBUG=INFO for details).  CUDA error:

Could you please share the NCCL debug log?

**Comment by trivialfis** [comment]
You can pass the environment variable using spark submit.

**Comment by trivialfis** [comment]
Hi @jjayadeep06, are you using GCP Dataproc? If so, please share your cluster creation command.

**Comment by jjayadeep06** [comment]
> You can pass the environment variable using spark submit.

Should this be passed via `spark.executorEnv` or `spark.yarn.appMasterEnv`. I am currently creating a the cluster with the below configuration

**Comment by jjayadeep06** [comment]
```
gcloud dataproc batches submit pyspark <SCRIPT_ID>  --project=<PROJECT_ID> --region=us-central1 --deps-bucket=<BUCKET_NAME> --properties=spark.dataproc.executor.compute.tier=premium,spark.dataproc.executor.disk.tier=premium,spark.dataproc.executor.resource.accelerator.type=a100-40,spark.dataproc.executor.disk.size=750g,spark.dataproc.driverEnv.LANG=C.UTF-8,spark.executorEnv.LANG=C.UTF-8,spark.shuffle.manager=com.nvidia.spark.rapids.RapidsShuffleManager,spark.task.resource.gpu.amount=1,spark.dynamicAllocation.enabled=false --network <NETWORK_ID>
```

This is the script I am submitting.

Should we need to implement [mig](https://docs.nvidia.com/spark-rapids/user-guide/latest/getting-started/google-cloud-dataproc.html#create-a-dataproc-cluster-using-mig-with-a100s) profile for it to work with `a2` GPU ?

**Comment by trivialfis** [comment]
Are you using MIG? Asking since NCCL doesn't support MIG yet. On the other hand, if you are using MIG, the error should come up before NCCL initialization.


> Should this be passed via `spark.executorEnv` or `spark.yarn.appMasterEnv`.

Executor. The spark submit argument:

```
  --conf spark.executorEnv.NCCL_DEBUG=INFO
```
It should print some error messages to the executor log. I can't remember whether it's stdout or stderr.

**Comment by trivialfis** [comment]
> Looks like it is an OOM error and I believe I might need to tune spark gpu properties to make it work. Is my understanding correct?

Correct. Before digging into memory usage optimization, please ensure memory pools (if any) do not take up all the GPU memory. It's unusual for NCCL to run into an OOM error.

Based on your launch parameter, the memory pool is NOT enabled, I think (not an expert), but it's still worth verifying. A simple way to do it is to check that the worker's memory usage doesn't spike at the beginning. If memory pool is involved, then you need to make sure both pools from the Python process and the Jvm process are correctly configured.

If no memory pool is involved. Then it's probably pyspark being greedy, it needs two copies of data, one for JVM and one for Python. I will defer that to @wbo4958 and @WeichenXu123 for spark-related details.

**Comment by jjayadeep06** [comment]
Another question, for spark.xgboost can we run a cluster with master[cpu] and worker[gpu] or does everything need to run on [gpu]. If we use master [cpu] and worker[gpu] then I see the below warning:-

```
2025-05-14 19:19:21,032 INFO XGBoost-PySpark: _fit Finished xgboost training!
/opt/conda/default/lib/python3.11/site-packages/xgboost/core.py:158: UserWarning: [19:19:22] WARNING: /home/conda/feedstock_root/build_artifacts/xgboost-split_1744329155408/work/src/gbm/gbtree.cc:388: Changing updater from `grow_gpu_hist` to `grow_quantile_histmaker`.
  warnings.warn(smsg, UserWarning)
/opt/conda/default/lib/python3.11/site-packages/xgboost/core.py:158: UserWarning: [19:19:22] WARNING: /home/conda/feedstock_root/build_artifacts/xgboost-split_1744329155408/work/src/context.cc:43: No visible GPU is found, setting device to CPU.
  warnings.warn(smsg, UserWarning)
```

This goes away if we use gpu for all the machines. 

If we look at the warning it comes up after `_fit` method is called and is completed. This means that the training has already finished....therefore can this warning be ignored,  but then it also has this warning line `Changing updater from `grow_gpu_hist` to `grow_quantile_histmaker`. 

My assumption is that the training happens in the executor which has the GPU and therefore this can be ignored.

**Comment by wbo4958** [comment]
Hi @jjayadeep06, Have you figured out the OOM issue? Is there anything I can help? BTW, did you use spark-rapids to accelerate it?

**Comment by jjayadeep06** [comment]
Hi @wbo4958 - I was able to solve the problem by setting `spark.rapids.memory.gpu.pool` to `None`. Looks like the Spark RAPIDS RMM was causing the OOM. I could not find much documentation around this in spark rapids document. Do you have any recommendations on what are the ideal parameters to set and its values if we run `Spark ML` workload ?

**Comment by viadea** [comment]
@jjayadeep06  We have example here https://github.com/NVIDIA/spark-rapids-examples/blob/main/docs/get-started/xgboost-examples/on-prem-cluster/standalone-python.md and doc here https://docs.nvidia.com/spark-rapids/user-guide/latest/additional-functionality/ml-integration.html . Yes. we need to disable RMM. Does it mean, this issue is resolved after setting it none?

**Comment by jjayadeep06** [comment]
Yes, the issue is resolved. Thanks everyone !
