### ISSUE TITLE
XGBoost PyPi package seems to lack CUDA support

### ISSUE THREAD

**Issue by Aman-Surkar** [dmlc/xgboost#11482]
Hello Team,
I installed XGBoost==3.0.1 via pip from PyPI, and when I try to run a test using device='cuda', I get this warning:
` WARNING: /workspace/src/context.cc:196: XGBoost is not compiled with CUDA support.`
Even though I’ve specified device='cuda', it still runs on CPU. Just wanted to check — does the PyPI version not come with GPU/CUDA support?
I am using UBI9 nvidia CUDA 12.6 x86 container.
when I run below sample program:
```
import numpy as np
import xgboost as xgb
xgb_model = xgb.XGBRegressor( # tree_method="gpu_hist" # deprecated
    tree_method="hist",
    device="cuda"
)
X = np.random.rand(50, 2)
y = np.random.randint(2, size=50)
xgb_model.fit(X, y)
print(xgb_model )
```
error message i get:
```
/home/builder/test/lib64/python3.9/site-packages/xgboost/core.py:158: UserWarning: [11:40:57] WARNING: /workspace/src/context.cc:43: No visible GPU is found, setting device to CPU.
  warnings.warn(smsg, UserWarning)
/home/builder/test/lib64/python3.9/site-packages/xgboost/core.py:158: UserWarning: [11:40:57] WARNING: /workspace/src/context.cc:196: XGBoost is not compiled with CUDA support.
  warnings.warn(smsg, UserWarning)
XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device='cuda', early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             gamma=None, grow_policy=None, importance_type=None,
             interaction_constraints=None, learning_rate=None, max_bin=None,
             max_cat_threshold=None, max_cat_to_onehot=None,
             max_delta_step=None, max_depth=None, max_leaves=None,
             min_child_weight=None, missing=nan, monotone_constraints=None,
             multi_strategy=None, n_estimators=None, n_jobs=None,
             num_parallel_tree=None, random_state=None, ...)
```

**Comment by hcho3** [comment]
Can you post the log from the install command? (`pip install xgboost`)? Let's make sure we are downloading `xgboost-3.0.1-py3-none-manylinux_2_28_x86_64.whl` (which has CUDA support), not `xgboost-3.0.1-py3-none-manylinux2014_x86_64.whl` (which does not have CUDA support).

**Comment by Aman-Surkar** [comment]
Hi, I have added the installation logs below:
```
(xgb-test) [builder@0e89b84db032 ~]$ pip install xgboost
Collecting xgboost
  Obtaining dependency information for xgboost from https://files.pythonhosted.org/packages/fd/b8/25788d4e7fa8346647afcdf93abe5c1333af88e4a740cb4355c11b6d8392/xgboost-3.0.1-py3-none-manylinux_2_28_x86_64.whl.metadata
  Downloading xgboost-3.0.1-py3-none-manylinux_2_28_x86_64.whl.metadata (2.1 kB)
Collecting numpy (from xgboost)
  Obtaining dependency information for numpy from https://files.pythonhosted.org/packages/8c/3d/1e1db36cfd41f895d266b103df00ca5b3cbe965184df824dec5c08c6b803/numpy-2.2.6-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata
  Downloading numpy-2.2.6-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (62 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.0/62.0 kB 1.1 MB/s eta 0:00:00
Collecting nvidia-nccl-cu12 (from xgboost)
  Obtaining dependency information for nvidia-nccl-cu12 from https://files.pythonhosted.org/packages/48/fb/ec4ac065d9b0d56f72eaf1d9b0df601e33da28197b32ca351dc05b342611/nvidia_nccl_cu12-2.26.5-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata
  Downloading nvidia_nccl_cu12-2.26.5-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (2.0 kB)
Collecting scipy (from xgboost)
  Obtaining dependency information for scipy from https://files.pythonhosted.org/packages/0b/1f/03f52c282437a168ee2c7c14a1a0d0781a9a4a8962d84ac05c06b4c5b555/scipy-1.15.3-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata
  Downloading scipy-1.15.3-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (61 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.0/62.0 kB 3.3 MB/s eta 0:00:00
Downloading xgboost-3.0.1-py3-none-manylinux_2_28_x86_64.whl (253.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 253.9/253.9 MB 730.9 kB/s eta 0:00:00
Downloading numpy-2.2.6-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (16.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.5/16.5 MB 1.2 MB/s eta 0:00:00
Downloading nvidia_nccl_cu12-2.26.5-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (318.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 318.1/318.1 MB 6.5 MB/s eta 0:00:00
Downloading scipy-1.15.3-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (37.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 37.3/37.3 MB 6.2 MB/s eta 0:00:00
Installing collected packages: nvidia-nccl-cu12, numpy, scipy, xgboost
Successfully installed numpy-2.2.6 nvidia-nccl-cu12-2.26.5 scipy-1.15.3 xgboost-3.0.1

```

**Comment by Aman-Surkar** [comment]
The test logs:
```
(xgb-test) [builder@0e89b84db032 ~]$ python xgboost_test.py
/home/builder/xgb-test/lib64/python3.12/site-packages/xgboost/training.py:183: UserWarning: [09:06:37] WARNING: /workspace/src/context.cc:49: No visible GPU is found, setting device to CPU.
  bst.update(dtrain, iteration=i, fobj=obj)
/home/builder/xgb-test/lib64/python3.12/site-packages/xgboost/training.py:183: UserWarning: [09:06:37] WARNING: /workspace/src/context.cc:203: XGBoost is not compiled with CUDA support.
  bst.update(dtrain, iteration=i, fobj=obj)
XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device='cuda', early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=None, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=None,
             n_jobs=None, num_parallel_tree=None, ...)
(xgb-test) [builder@0e89b84db032 ~]$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2024 NVIDIA Corporation
Built on Wed_Aug_14_10:10:22_PDT_2024
Cuda compilation tools, release 12.6, V12.6.68
Build cuda_12.6.r12.6/compiler.34714021_0
```

**Comment by Aman-Surkar** [comment]
Yes, it says nvidia-smi not a command:
```
(xgb-test) [builder@0e89b84db032 ~]$ nvidia-smi
bash: nvidia-smi: command not found

```

**Comment by trivialfis** [comment]
Hi, any update?

**Comment by Aman-Surkar** [comment]
Sorry, @trivialfis @hcho3 for late reply, thanks, I was able to resolve the issue with steps mentioned.

**Comment by trivialfis** [comment]
Happy to help!
