### ISSUE TITLE
Very long startup time with DaskQuantileDMatrix

### ISSUE THREAD

**Issue by jamesram415** [dmlc/xgboost#11529]
Hi - thanks for the great repo.

I am trying to run fitting with dask distributed and `DaskQuantileDMatrix`. I have 23M rows and two GPUs.

I notice a very long delay between the construction of my `dtrain` and the completion of the first boosting round. From then onwards, training is very fast.

I have been trying to debug this with the following minimal working example with a small numpy array. Looking at the code, I notice:

1. Reaching the line `dxgb.train` is relatively quick.
2. Internally `_get_dmatrices` within `_train_async` is the bottleneck. From my profiling it appears CPU utilisation is low for the 4 loops over the chunks.
3. I notice that calling `cp.asarray` on X/y/w prior to `da.from_array` leads to a massive speedup but causes a GPU OOM with the full dataset.

Currently with 23M rows it takes 12h to get to the first boosting round and then around 40m to complete training. 

Does it look like we are doing anything obviously wrong below? Is there any way to reduce the loading time?
Many thanks
```
import os
os.environ["BOKEH_RESOURCES"] = "inline"
from dask.distributed import Client
from dask_cuda import LocalCUDACluster
from xgboost import dask as dxgb
import numpy as np
import time
from dask.distributed import performance_report
import logging
from dask import array as da

logger = logging.getLogger(__name__)

booster_config = {
    "tree_method": "hist",
    "max_depth": 12,
    "max_bin": 16,
    "device": 'cuda',
    "verbosity": 1,
    "eta": 0.05,
    "lambda": 1,
    "subsample": 0.25,
    "colsample_bytree": 0.5, 
    "num_parallel_tree": 10,
    "multi_strategy": "one_output_per_tree",
    "objective": "reg:squarederror",
    "eval_metric": ["rmse"],
    "seed": 1,
    "sampling_method": "gradient_based"
}

NUM_GPUS = 1
TOTAL_ROWS = 100_000
NUM_ROUNDS = 1
MAX_BIN = 16
num_cols = 3285

def main():
    X, y, w = np.random.random((TOTAL_ROWS, num_cols)), np.random.random((TOTAL_ROWS,1)), np.random.random((TOTAL_ROWS,1))
    cluster = LocalCUDACluster(n_workers=NUM_GPUS, threads_per_worker=16, device_memory_limit=0.9)
    client = Client(cluster, direct_to_workers=True)
    with performance_report(filename="min_repro.html"):        
        # Chunk up the data into small partitions of order 100MB
        chunk_rows = 2500
        Xa  = da.from_array(X, chunks=(chunk_rows, -1), asarray=False)
        ya  = da.from_array(y, chunks=(chunk_rows, 1), asarray=False)
        wa  = da.from_array(w, chunks=(chunk_rows, 1), asarray=False)

        dtrain = dxgb.DaskQuantileDMatrix(client, Xa, ya, weight=wa, max_bin=MAX_BIN, ref=None)
        
        logger.info('starting training')
        start = time.time()
        dxgb.train(
            client,
            booster_config,
            dtrain=dtrain,
            num_boost_round=NUM_ROUNDS,
            xgb_model=None,
        )
        print(time.time() - start)

if __name__ == '__main__':
    main()
```

**Comment by jamesram415** [comment]
The Dask based approach above takes 80s for the `dxgb.train` whereas this non-dask approach takes 1s for the same number of rows

```
import os

import xgboost
os.environ["BOKEH_RESOURCES"] = "inline"
import numpy as np
import time
import logging
logger = logging.getLogger(__name__)

booster_config = {
    "tree_method": "hist",
    "max_depth": 12,
    "max_bin": 16,
    "device": 'cuda',
    "verbosity": 1,
    "eta": 0.05,
    "lambda": 1,
    "subsample": 0.25,
    "colsample_bytree": 0.5, 
    "num_parallel_tree": 10,
    "multi_strategy": "one_output_per_tree",
    "objective": "reg:squarederror",
    "eval_metric": ["rmse"],
    "seed": 1,
    "sampling_method": "gradient_based"
}

NUM_GPUS = 1
TOTAL_ROWS = 100_000
NUM_ROUNDS = 1
MAX_BIN = 16
num_cols = 3285

def main():
    X, y, w = np.random.random((TOTAL_ROWS, num_cols)), np.random.random((TOTAL_ROWS,1)), np.random.random((TOTAL_ROWS,1))
    dtrain = xgboost.QuantileDMatrix(X, y, weight=w, max_bin=16)
    
    logger.info('starting training')
    start = time.time()
    xgboost.train(
        booster_config,
        dtrain,
        num_boost_round=1,
        evals=None,        
        custom_metric=None,
    )
    print(time.time() - start)

if __name__ == '__main__':
    main()
```

**Comment by trivialfis** [comment]
Please take a look at the tutorial for dask https://xgboost.readthedocs.io/en/stable/tutorials/dask.html .

Here are some of my initial guesses, all discussed in the document linked above:
- Distributing np arrays can take a lot of time. Using dask to generate the data is preferred. (`da.random`). In general, one should not distribute data from the client to workers.
- The `DaskQuantileDMatrix` is where we materialize all the lazy computation. To measure the construction time, you need to sync the data with the client before the construction.

**Comment by jamesram415** [comment]
Interesting - looking at the dask example in the docs you link to, running that with equivalent data size is far faster than my script (approx 10s). 

With some trial and error - the change to get my script to the same speed is using `LocalCluster` instead of `LocalCUDACluster`.

Is there anything in the cuda cluster that could be adding overhead? I ran an nsys trace and it looks like the LocalCluster is still making use of the single GPU once training starts.

Unfortunately, I think I can't train on >1 GPU with the LocalCluster

**Comment by jamesram415** [comment]
Just to add a min reproducible example to the above finding:

Switching the cluster between `LocalCUDACluster` and `LocalCluster` makes a big difference (80s vs 13s) in the end to end training time.

```
from xgboost import dask as dxgb

import dask.array as da
import dask.distributed
from dask_cuda import LocalCUDACluster
import time
import numpy as np

booster_config = {
    "tree_method": "hist",
    "max_depth": 12,
    "max_bin": 16,
    "device": 'cuda',    
    "verbosity": 3,
    "eta": 0.05,
    "lambda": 1,
    "subsample": 0.25,
    "colsample_bytree": 0.5, 
    "num_parallel_tree": 10,
    "multi_strategy": "one_output_per_tree",
    "objective": "reg:squarederror",
    "eval_metric": ["rmse"],
    "seed": 1,
    "sampling_method": "gradient_based"
}

if __name__ == "__main__":

    # This is slow, around 80 seconds
    # cluster = LocalCUDACluster(n_workers=1)

    # This is faster, around 13seconds
    cluster = dask.distributed.LocalCluster(n_workers=1)

    client = dask.distributed.Client(cluster)

    # X and y must be Dask dataframes or arrays
    num_obs = 100_000
    num_features = 3285

    X = da.random.random(size=(num_obs, num_features), chunks=(1000, num_features))
    y = da.random.random(size=(num_obs, 1), chunks=(1000, 1))
    w = da.random.random(size=(num_obs, 1), chunks=(1000, 1))

    start = time.time()
    dtrain = dxgb.DaskQuantileDMatrix(client, X, y, w, max_bin=16)

    output = dxgb.train(
        client,
        booster_config,
        dtrain,
        num_boost_round=1,
    )
    print(time.time() - start)

```

**Comment by trivialfis** [comment]
The `LocalCUDACluster` uses a single thread by default, you need to set the `threads_per_worker` parameter as shown in this example https://xgboost.readthedocs.io/en/stable/python/dask-examples/gpu_training.html#sphx-glr-python-dask-examples-gpu-training-py .

**Comment by jamesram415** [comment]
Ah we already tried that with 4, 8, 16 threads but still no luck - at best it reduces from 80s to 77s.

Out of interest are you able to repro this? I'm curious if it is related to our setup somehow.

**Comment by trivialfis** [comment]
Using the snippet provided in https://github.com/dmlc/xgboost/issues/11529#issuecomment-3005563819 , I have  tested the following configurations:
- `LocalCluster(n_workers=1)`, the duration is `4.965837478637695`.
- `LocalCUDACluster(n_workers=1, threads_per_worker=os.cpu_count())`, the duration is `5.395801067352295`.

I'm using:
- CPU: AMD Ryzen Threadripper PRO 5975WX 32-Cores
- GPU: NVIDIA RTX A6000

**Comment by jamesram415** [comment]
That's useful thanks.

I have an NVIDIA A100 and a driver without RMM support. Though it appears the slow part (`_get_dmatrices`) occurs before anything has needed to touch the GPU.

Is there anything you think it would be worth trying/looking into?

Cuda cluster trace:
![Image](https://github.com/user-attachments/assets/08b667fa-474e-48f8-93d9-f72e6474ce2b)

local cluster trace
![Image](https://github.com/user-attachments/assets/16db18e4-4c32-48ed-bf3a-a13ee74abfb4)

**Comment by trivialfis** [comment]
Perhaps use a larger chunk size than 1000?

**Comment by jamesram415** [comment]
Tried that, no luck unfortunately

**Comment by trivialfis** [comment]
I can't make any more guesses. I can get access to A100, but before that, it would be great if you could share more details on your environment and the exact script that you are using. For the environment:
- XGBoost version.
- Dask/Distributed version.
- Dask-CUDA version.
- numpy version
- cupy version

**Comment by jamesram415** [comment]
Sure:
xgboost==3.0.2 
dask==2025.5.0
dask-cuda==25.6.0
numpy==2.2.6
cupy-cuda12x==13.4.1
Python 3.10.12

The script is exactly the one above that you ran. I added some nsys profiling to get the above traces.

~Incidentally I have noticed that within the `init` method of `LocalCUDACluster` if I override the call to the superclass (LocalCluster) to set `num_workers` > 0 it appears to fix things. Just checking if this works more than one gpu.~


--- 
I also just upgraded to ``` dask-2025.5.1 distributed-2025.5.1 ``` and no luck

**Comment by jamesram415** [comment]
I seemingly have the same issue on a H200

**Comment by trivialfis** [comment]
Tested on a H100, did not reproduce.
```
   - numpy=2.2
   - cupy=13.4
   - dask[version='>=2025.5']
   - distributed[version='>=2025.5']
   - dask-cuda[version='>=25.6*']
```
time:
```
7.072886943817139
```

**Comment by jamesram415** [comment]
Turns out this is fixed after adding: `dask.config.set({"array.backend": "cupy"})` - it looks like this moved the _get_dmatrices code onto GPU 

Perhaps you have this set in an env variable? could explain why it was not reproducible 

Thanks

**Comment by trivialfis** [comment]
No, I don't have such environment variable.
