### ISSUE TITLE
NCCL error with simple dask example

### ISSUE THREAD

**Issue by jamesram415** [dmlc/xgboost#11726]
Hi,

The snippet below fails with a NCCL error.

At first I thought it was when `n_workers > 1` but it appears to also be the case for a single worker.

I'm not sure if this is due to a recent library change as I believe this code used to work fine.

```
from xgboost import dask as dxgb

import dask.array as da
import dask.distributed
from dask_cuda import LocalCUDACluster

if __name__ == "__main__":
    # cluster = dask.distributed.LocalCluster()
    cluster = LocalCUDACluster(n_workers=1)
    client = dask.distributed.Client(cluster)

    # X and y must be Dask dataframes or arrays
    num_obs = 1e5
    num_features = 20
    dask.config.set({"array.backend": "cupy"})
    X = da.random.random(size=(num_obs, num_features), chunks=(1000, num_features))
    y = da.random.random(size=(num_obs, 1), chunks=(1000, 1))

    dtrain = dxgb.DaskDMatrix(client, X, y)
    # or
    # dtrain = dxgb.DaskQuantileDMatrix(client, X, y)

    output = dxgb.train(
        client,
        {"verbosity": 2, "tree_method": "hist", "objective": "reg:squarederror", "device": "cuda"},
        dtrain,
        num_boost_round=4,
        evals=[(dtrain, "train")],
    )

    print('done!')
```

Env:
```
cupy-cuda12x==13.6.0
dask-cuda==25.8.0
dask==2025.7.0
dask-cuda==25.8.0
rapids-dask-dependency==25.8.0   
cupy-cuda12x==13.6.0
xgboost==3.0.5  
  
Cuda 12.8
```

```
  File "/home/admin/simple_test/xgb/lib/python3.12/site-packages/xgboost/training.py", line 183, in train
    bst.update(dtrain, iteration=i, fobj=obj)
  ^^^^^^^^^^^^^^^^^
  File "/home/admin/simple_test/xgb/lib/python3.12/site-packages/xgboost/core.py", line 2246, in update
    _check_call(
^^^^^^^^^^^^^^^
  File "/home/admin/simple_test/xgb/lib/python3.12/site-packages/xgboost/core.py", line 310, in _check_call
    raise XGBoostError(py_str(_LIB.XGBGetLastError()))
  ^^^^^^^^^^^^^^^^^
xgboost.core.XGBoostError: [12:56:26] /workspace/src/collective/result.cc:78: 
- [nccl_stub.cc:49|12:56:26]: NCCL failure: unhandled cuda error (run with NCCL_DEBUG=INFO for details).  CUDA error: 

Stack trace:
  [bt] (0) /home/admin/simple_test/xgb/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x2a6e7c) [0x7f15434a6e7c]
  [bt] (1) /home/admin/simple_test/xgb/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x364e21) [0x7f1543564e21]
  [bt] (2) /home/admin/simple_test/xgb/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0xa59779) [0x7f1543c59779]
  [bt] (3) /home/admin/simple_test/xgb/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0xa5a1f9) [0x7f1543c5a1f9]
  [bt] (4) /home/admin/simple_test/xgb/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x33e3b5) [0x7f154353e3b5]
  [bt] (5) /home/admin/simple_test/xgb/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x3d2268) [0x7f15435d2268]
  [bt] (6) /home/admin/simple_test/xgb/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0xb73367) [0x7f1543d73367]
  [bt] (7) /home/admin/simple_test/xgb/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x450c58) [0x7f1543650c58]
  [bt] (8) /home/admin/simple_test/xgb/lib/python3.12/site-packages/xgboost/lib/libxgboost.so(+0x7270a2) [0x7f15439270a2]
```

This is on an A100

**Comment by trivialfis** [comment]
Could you please enable and share the NCCL debug log https://docs.nvidia.com/deeplearning/nccl/user-guide/docs/env.html ?

**Comment by jamesram415** [comment]
Ah it turned out I installed a more recent NCCL version that was not compatible with the runtime
