### ISSUE TITLE
Problems with k80 GPUs on AWS

### ISSUE THREAD

**Issue by RAMitchell** [dmlc/xgboost#3264]
The 'gpu_hist' algorithm is currently failing unit tests on a k80 GPU. The script below shows worse accuracy for the GPU algorithm vs the CPU specifically on this GPU. Running it multiple times and diffing the model shows the split calculations randomly changing in some places on subsequent runs - this bug is nondeterministic. I also cannot reproduce it on Pascal GPUs.

I can think of a few possible causes:
- Something is wrong with the CAS version of atomic add that is used on this older architecture
- Some part of the program is writing to areas of memory it shouldn't be. This would possibly not be picked up as an illegal memory access due to our bulk allocation strategy
- Some other problem with the hardware setup

@teju85 @canonizer I would appreciate your input here, I'm pretty stumped.

This problem is preventing me setting up our new continuous integration for the GPU build as this needs to run on a p2.xlarge instance.

## Environment info
Operating System:
Ubuntu 16.04
Deep Learning AMI (Ubuntu) Version 7.0 (ami-e65e4d9a)
AWS p2.xlarge
Compiler:
cuda 9.0
Package used (python/R/jvm/C++):
python
`xgboost` version used:
Latest from source: 25b2919c448615abc0943ae8e0bad0898886c7f0

Script to reproduce:
```
import xgboost as xgb
import numpy as np
from sklearn.datasets import make_regression

rng = np.random.RandomState(1994)
comparison_tree_method = "hist"
param = {'tree_method': 'gpu_hist', 'grow_policy': 'depthwise', 'max_bin': 1024, 'max_depth':  4, 'max_leaves': 255,
         'n_gpus': 1}
n = 5000
sparsity = 0.75
X, y = make_regression(n, random_state=rng)
X = np.array([[np.nan if rng.uniform(0, 1) < sparsity else x for x in x_row] for x_row in X])
dtrain = xgb.DMatrix(X, label=y)
res_tmp = {}
res = {}
num_rounds = 10

bst = xgb.train(param, dtrain, num_rounds, [(dtrain, 'train')], evals_result=res_tmp)
bst.dump_model("gpu.model", with_stats=True)
res[param['tree_method']] = res_tmp['train']['rmse']
param["tree_method"] = comparison_tree_method
bst = xgb.train(param, dtrain, num_rounds, [(dtrain, 'train')], evals_result=res_tmp)
bst.dump_model("cpu.model", with_stats=True)

```

**Comment by teju85** [comment]
I see. I too think that on the surface, it appears to be some issue with atomics.
Looking further. Will get back soon with my findings.

**Comment by StudyExchange** [comment]
@RAMitchell , how do you configure the xgboost gpu env at AWS K80s. In addition, Is your AWS K80 p2.xlarge?

**Comment by teju85** [comment]
@RAMitchell 
The progress on this has been slower than expected, since this issue reproduces probabilitistically. Interestingly though, when I dumped the "hist.GetHistPtr" contents for the failing and passing cases (both on GPU), their contents seem to be the same! However, the node's loss_chg (and thus also fvalue and fidx) is different. This makes me think that something bad is happening outside of BuildHist.

Looking further...

**Comment by teju85** [comment]
This turns out to be an issue with the ReduceFeature function inside updater_gpu_hist.cu.
The 'Reduce' call to cub with a temporary storage in shared mem was inside a loop, without a barrier.
So, there was a chance of this temp storage getting overwritten across loop iterations.
After fixing this, I'm able to match the output of CPU and GPU. (pasted output at the end of this message)

I don't yet have an explanation as to how this has been working on Maxwell/Pascal/Volta, but fails only on Kepler!

```bash
$ python ../old-k80.py
[07:15:32] Allocated 0MB on [0] Tesla K80, 11352MB remaining.
[07:15:32] Allocated 795MB on [0] Tesla K80, 10557MB remaining.
[0]     train-rmse:125.613
[1]     train-rmse:122.465
[2]     train-rmse:120.229
[3]     train-rmse:118.384
[4]     train-rmse:117.086
[5]     train-rmse:115.804
[6]     train-rmse:114.655
[7]     train-rmse:113.494
[8]     train-rmse:112.584
[9]     train-rmse:111.689
[07:15:33] Tree method is selected to be 'hist', which uses a single updater grow_fast_histmaker.
[07:15:33] /work/boosting/xgboost/src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 30 extra nodes, 0 pruned nodes, max_depth=4
[0]     train-rmse:125.613
[07:15:33] /work/boosting/xgboost/src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 28 extra nodes, 0 pruned nodes, max_depth=4
[1]     train-rmse:122.465
[07:15:33] /work/boosting/xgboost/src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 30 extra nodes, 0 pruned nodes, max_depth=4
[2]     train-rmse:120.229
[07:15:33] /work/boosting/xgboost/src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 28 extra nodes, 0 pruned nodes, max_depth=4
[3]     train-rmse:118.384
[07:15:33] /work/boosting/xgboost/src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 30 extra nodes, 0 pruned nodes, max_depth=4
[4]     train-rmse:117.086
[07:15:33] /work/boosting/xgboost/src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 30 extra nodes, 0 pruned nodes, max_depth=4
[5]     train-rmse:115.804
[07:15:33] /work/boosting/xgboost/src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 30 extra nodes, 0 pruned nodes, max_depth=4
[6]     train-rmse:114.655
[07:15:33] /work/boosting/xgboost/src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 30 extra nodes, 0 pruned nodes, max_depth=4
[7]     train-rmse:113.494
[07:15:33] /work/boosting/xgboost/src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 28 extra nodes, 0 pruned nodes, max_depth=4
[8]     train-rmse:112.584
[07:15:33] /work/boosting/xgboost/src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 28 extra nodes, 0 pruned nodes, max_depth=4
[9]     train-rmse:111.689
```

**Comment by teju85** [comment]
@RAMitchell Can you review and merge this fix?

**Comment by pkit** [comment]
@teju85 still fails for me on K80 after the fix:
```
('depthwise', 2, 2, 255, 1)
{'n_gpus': 1, 'grow_policy': 'depthwise', 'max_leaves': 255, 'max_bin': 2, 'tree_method': 'gpu_hist', 'max_depth': 2}
[13:49:09] Allocated 0MB on [0] Tesla K80, 11365MB remaining.
[13:49:09] Allocated 0MB on [0] Tesla K80, 11364MB remaining.
[0]	train-rmse:17.8628
[1]	train-rmse:13.9968
[2]	train-rmse:11.2418
[3]	train-rmse:9.60072
[4]	train-rmse:8.68026
[5]	train-rmse:8.18956
[6]	train-rmse:7.79987
[7]	train-rmse:7.40074
[8]	train-rmse:7.18481
[9]	train-rmse:6.93253
[13:49:09] Tree method is selected to be 'hist', which uses a single updater grow_fast_histmaker.
[13:49:09] /tmp/qbld/20180503/build/src/xgboost_v2-0.71.post1/src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 6 extra nodes, 0 pruned nodes, max_depth=2
[0]	train-rmse:17.5461
[13:49:09] /tmp/qbld/20180503/build/src/xgboost_v2-0.71.post1/src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 6 extra nodes, 0 pruned nodes, max_depth=2
[1]	train-rmse:13.2139
[13:49:09] /tmp/qbld/20180503/build/src/xgboost_v2-0.71.post1/src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 6 extra nodes, 0 pruned nodes, max_depth=2
[2]	train-rmse:10.4809
[13:49:09] /tmp/qbld/20180503/build/src/xgboost_v2-0.71.post1/src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 6 extra nodes, 0 pruned nodes, max_depth=2
[3]	train-rmse:8.71713
[13:49:09] /tmp/qbld/20180503/build/src/xgboost_v2-0.71.post1/src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 6 extra nodes, 0 pruned nodes, max_depth=2
[4]	train-rmse:7.70695
[13:49:09] /tmp/qbld/20180503/build/src/xgboost_v2-0.71.post1/src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 6 extra nodes, 0 pruned nodes, max_depth=2
[5]	train-rmse:7.13242
[13:49:09] /tmp/qbld/20180503/build/src/xgboost_v2-0.71.post1/src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 6 extra nodes, 0 pruned nodes, max_depth=2
[6]	train-rmse:6.79147
[13:49:09] /tmp/qbld/20180503/build/src/xgboost_v2-0.71.post1/src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 6 extra nodes, 0 pruned nodes, max_depth=2
[7]	train-rmse:6.5955
[13:49:09] /tmp/qbld/20180503/build/src/xgboost_v2-0.71.post1/src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 6 extra nodes, 0 pruned nodes, max_depth=2
[8]	train-rmse:6.48949
[13:49:09] /tmp/qbld/20180503/build/src/xgboost_v2-0.71.post1/src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 6 extra nodes, 0 pruned nodes, max_depth=2
[9]	train-rmse:6.39231
F

================================================================================================= FAILURES =================================================================================================
__________________________________________________________________________________________ TestGPU.test_gpu_hist ___________________________________________________________________________________________

self = <test_gpu_updaters.TestGPU testMethod=test_gpu_hist>

    def test_gpu_hist(self):
        variable_param = {'n_gpus': [1, -1], 'max_depth': [2, 6], 'max_leaves': [255, 4], 'max_bin': [2, 16, 1024],
                          'grow_policy': ['depthwise', 'lossguide']}
>       assert_updater_accuracy('gpu_hist', 'hist', variable_param, 0.01)

tests/python-gpu/test_gpu_updaters.py:131: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
tests/python-gpu/test_gpu_updaters.py:113: in assert_updater_accuracy
    param_tmp)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

res = {'gpu_hist': [17.862795, 13.996805, 11.241832, 9.600716, 8.680255, 8.189556, ...], 'hist': [17.546087, 13.21392, 10.480869, 8.717126, 7.706947, 7.132425, ...]}, tree_method = 'gpu_hist'
comparison_tree_method = 'hist', tolerance = 0.01, param = {'grow_policy': 'depthwise', 'max_bin': 2, 'max_depth': 2, 'max_leaves': 255, ...}

    def assert_accuracy(res, tree_method, comparison_tree_method, tolerance, param):
        assert non_increasing(res[tree_method], tolerance)
>       assert np.allclose(res[tree_method][-1], res[comparison_tree_method][-1], 1e-3, 1e-2)
E       AssertionError: assert <function allclose at 0x2d51758>(6.932528, 6.392306, 0.001, 0.01)
E        +  where <function allclose at 0x2d51758> = np.allclose

tests/python-gpu/test_gpu_updaters.py:23: AssertionError
==================================================================================== 1 failed, 1 passed in 8.20 seconds =================================================================
```

**Comment by RAMitchell** [comment]
Unit tests pass for me. Many thanks for solving this @teju85. @pkit can you please try removing all existing XGBoost installations then try again.

**Comment by pkit** [comment]
@RAMitchell I was using 0.71 release code and just "backported" this patch there.
Will re-try with master.
