### ISSUE TITLE
compiler error: argument of type "void *" is incompatible with parameter of type "int *"

### ISSUE THREAD

**Issue by se-l** [dmlc/xgboost#3320]
For bugs or installation issues, please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

## Environment info
Operating System: Ubuntu 16.04

Compiler: cmake 3.94 with gcc-5.5
also cmake 3.11 with gcc-5.5

Package used (python/R/jvm/C++): compiler issue

`xgboost` version used: 7 commit  49b9f39

If installing from source, please provide 

1. The commit hash (`git rev-parse HEAD`)   49b9f39
2. Logs will be helpful (If logs are large, please upload as attachment).

**/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512fintrin.h(9481): error: argument of type "void *" is incompatible with parameter of type "int *"**

[gcc5-5.txt](https://github.com/dmlc/xgboost/files/2002127/gcc5-5.txt)

If you are using jvm package, please 

1. add [jvm-packages] in the title to make it quickly be identified
2. the gcc version and distribution
gcc-5.5
## Steps to reproduce

1.git clone --recursive https://github.com/dmlc/xgboost
    cd xgboost; git submodule update --init --recursive; mkdir build; cd build
2. cmake .. -DUSE_CUDA=ON
3.

## What have you tried?

1.  cmake .. -DUSE_CUDA=ON -DCMAKE_C_COMPILER=gcc-4.8 -DCMAKE_CXX_COMPILER=g++-4.8
successful compiling, but during training returns

xgboost.core.XGBoostError: b'[18:59:56] /home/ubuntu/repos/xgboost/src/learner.cc:153: XGBoost version not compiled with GPU support.\n\nStack trace returned 10 entries:\n[bt] (0) /home/ubuntu/anaconda3/envs/trade/lib/python3.6/site-packages/xgboost-0.71-py3.6.egg/xgboost/libxgboost.so(dmlc::StackTrace()+0x3d) [0x7f659b8e227d]\n[bt] (1) /home/ubuntu/anaconda3/envs/trade/lib/python3.6/site-packages/xgboost-0.71-py3.6.egg/xgboost/libxgboost.so(dmlc::LogMessageFatal::~LogMessageFatal()+0x18) [0x7f659b8e2698]\n[bt] (2) /home/ubuntu/anaconda3/envs/trade/lib/python3.6/site-packages/xgboost-0.71-py3.6.egg/xgboost/libxgboost.so(xgboost::LearnerImpl::ConfigureUpdaters()+0x112) [0x7f659b977ae2]\n[bt] (3) /home/ubuntu/anaconda3/envs/trade/lib/python3.6/site-packages/xgboost-0.71-py3.6.egg/xgboost/libxgboost.so(xgboost::LearnerImpl::Configure(std::vector<std::pair<std::string, std::string>, std::allocator<std::pair<std::string, std::string> > > const&)+0x467) [0x7f659b979bb7]\n[bt] (4) /home/ubuntu/anaconda3/envs/trade/lib/python3.6/site-packages/xgboost-0.71-py3.6.egg/xgboost/libxgboost.so(XGBoosterUpdateOneIter+0x5e) [0x7f659b8d9a1e]\n[bt] (5) /home/ubuntu/anaconda3/envs/trade/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(ffi_call_unix64+0x4c) [0x7f65b4615550]\n[bt] (6) /home/ubuntu/anaconda3/envs/trade/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(ffi_call+0x1f5) [0x7f65b4614cf5]\n[bt] (7) /home/ubuntu/anaconda3/envs/trade/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(_ctypes_callproc+0x3dc) [0x7f65b460c83c]\n[bt] (8) /home/ubuntu/anaconda3/envs/trade/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(+0x9da3) [0x7f65b4604da3]\n[bt] (9) /home/ubuntu/anaconda3/envs/trade/bin/../lib/libpython3.6m.so.1.0(_PyObject_FastCallDict+0x9e) [0x7f65c17b6ade]\n\n'

2.  or alternatively some compiled and installed, then returning 
'thrust:illegal memory access issue. different topic'
3.tried compiling from 13e7a2c. fails. message was cannot find -ldml-core

**Comment by se-l** [comment]
fixed after setting new instance with gcc 5.4.0 instead of 5.5. see also posts on which gcc is supported by which cuda 8 version. 8.0.61 supports apparently gcc 5.4.0 unfortunately still running into   'thrust:illegal memory access ' bug
