### ISSUE TITLE
xgboost hangs on ncclAllReduce

### ISSUE THREAD

**Issue by sh1ng** [dmlc/xgboost#4523]
Reproducible on ppc, haven't see in on x86_64
More details https://github.com/h2oai/h2o4gpu/issues/773
nccl: v2.4.2-1 installed from sources

Looks similar to https://github.com/dmlc/xgboost/issues/4107

**Comment by sh1ng** [comment]
Also happens on x86_64 and nccl 2.4.7
@trivialfis any ideas?

**Comment by trivialfis** [comment]
Will look into this.

**Comment by trivialfis** [comment]
@sh1ng @pseudotensor I factored out:

https://github.com/h2oai/h2o4gpu/blob/master/tests/python/open_data/gbm/test_xgboost.py

and

https://github.com/h2oai/h2o4gpu/blob/master/tests/python/open_data/gbm/test_gpu_prediction_pickledmodel.py

Compiled nccl v2.4.7-1 on Ubuntu 18.10 x86_64.  Ran above tests 5 times each with `n_gpus` set to 2, and haven't see seen any issue so far.

**Comment by RAMitchell** [comment]
One cause of this can be an unexpected number of threads in the team for omp. For example if there are two GPUs but only one thread available the thread will call nccl and then wait for the other GPU to sync, but there is no other thread concurrently running. You could do some diagnostics using omp functions to see how many threads are active.

**Comment by sh1ng** [comment]
@trivialfis I've seen it on x86_64(centos docker container) only once, but it's easily reproducible on ppc  

@RAMitchell thanks for the hint

**Comment by sh1ng** [comment]
Bu default sklear wrapper uses 1 thread https://github.com/dmlc/xgboost/blob/master/python-package/xgboost/sklearn.py#L244
and the parameter sets global openmp settings

v0.9 
https://github.com/dmlc/xgboost/blob/v0.90/src/common/device_helpers.cuh#L1047
will definitely hang 

It's fixed in master
https://github.com/dmlc/xgboost/blob/master/src/common/device_helpers.cuh#L1175

**Comment by trivialfis** [comment]
@sh1ng Thanks!  Let me add a check.

**Comment by sh1ng** [comment]
If it's confirmed, are you going to release a patch for v0.9?

**Comment by trivialfis** [comment]
@sh1ng I can backport a patch for you to apply it.  But currently @hcho3 is unavailable so I don't think we can make a new release.

**Comment by sh1ng** [comment]
I've fixed it in our fork.
