### ISSUE TITLE
XGBoost version not compiled with GPU support, even though it is

### ISSUE THREAD

**Issue by leedrake5** [dmlc/xgboost#4725]
It has been a long road to installation, but here's what works for Ubuntu 18.04 and R 3.6.1:

#Cuda 10.0 + NCCL 2.4.7
###install OS agnostic NCCL and put it in /usr/local/nccl-2.4.7
#remove all symlinks to usr/local/cuda and usr/bin/nvcc
```
cd /home/<user>/Software
sudo rm -R xgboost

git clone --recursive https://github.com/dmlc/xgboost
cd xgboost
mkdir build
cd build

cmake -DUSE_CUDA=ON -DR_LIB=ON -DR_LIB=ON -DUSE_NCCL=ON -DCUDA_TOOLKIT_ROOT_DIR=/usr/local/cuda-10.0 -DNCCL_ROOT=/usr/local/nccl-2.4.7 ..
sudo make -j4
```

This installs successfully. After this, I compile the R package

```
cd /home/<user>/Software/xgboost
sudo R CMD INSTALL R-package

```

This all works, and to my knowledge I've done everything right to enable GPU support. But when I run test data:

```
library(xgboost)
library(rBayesianOptimization)
data(agaricus.train, package = "xgboost")
 dtrain <- xgb.DMatrix(agaricus.train$data,
                       label = agaricus.train$label)
 cv_folds <- KFold(agaricus.train$label, nfolds = 5,
                   stratified = TRUE, seed = 0)
 xgb_cv_bayes <- function(max_depth, min_child_weight, subsample) {
   cv <- xgb.cv(params = list(booster = "gbtree", eta = 0.01,
                              max_depth = max_depth,
                              min_child_weight = min_child_weight,
                              subsample = subsample, colsample_bytree = 0.3,
                              lambda = 1, alpha = 0,
                              objective = "reg:linear",
                              eval_metric = "rmse"),
                data = dtrain, nround = 10,
                folds = cv_folds, prediction = TRUE, showsd = TRUE,
                early_stopping_rounds = 5, tree_method = 'gpu_hist', n_gpus=-1,maximize = TRUE, verbose = 0)
   list(Score = cv$evaluation_log$test_rmse_mean[cv$best_iteration],
        Pred = cv$pred)
 }
 OPT_Res <- BayesianOptimization(xgb_cv_bayes,
                                 bounds = list(max_depth = c(2L, 6L),
                                               min_child_weight = c(1L, 10L),
                                               subsample = c(0.5, 0.8)),
                                 init_grid_dt = NULL, init_points = 10, n_iter = 2,
                                 acq = "ucb", kappa = 2.576, eps = 0.0, verbose = TRUE)

```

I get the following error:

> Error in xgb.iter.update(fd$bst, fd$dtrain, iteration - 1, obj) : 
>   [16:27:55] ../..//amalgamation/../src/gbm/gbtree.h:153: XGBoost version not compiled with GPU support.
> Stack trace:
>   [bt] (0) /usr/local/lib/R/site-library/xgboost/libs/xgboost.so(dmlc::LogMessageFatal::~LogMessageFatal()+0x32) [0x7f022ef6bac2]
>   [bt] (1) /usr/local/lib/R/site-library/xgboost/libs/xgboost.so(xgboost::gbm::GBTree::AssertGPUSupport()+0x4f) [0x7f022efaf17f]
>   [bt] (2) /usr/local/lib/R/site-library/xgboost/libs/xgboost.so(xgboost::gbm::GBTree::ConfigureUpdaters(std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > const&)+0x195) [0x7f022ef80555]
>   [bt] (3) /usr/
> Timing stopped at: 0.035 0 0.009

I'm at a complete loss for why this didn't work. I have tried remove.packages("xgboost"), and re-installed from the source package using the dmlc/xgboost installation instructions. But still, it doesn't work.

**Comment by hcho3** [comment]
You should not use `sudo R CMD INSTALL R-package` here. Instead, run `make install` instead:
```
cmake -DUSE_CUDA=ON -DR_LIB=ON -DR_LIB=ON -DUSE_NCCL=ON -DCUDA_TOOLKIT_ROOT_DIR=/usr/local/cuda-10.0 -DNCCL_ROOT=/usr/local/nccl-2.4.7 ..
sudo make -j4
sudo make install
```

Also, make sure to remove the CRAN XGBoost package first.

**Comment by hcho3** [comment]
Aside: it is unfortunate that we are not able to put GPU-enabled XGBoost to CRAN (The Comprehensive R Archive Network). The reason is that CRAN requires that packages be portable to many platforms, including Solaris. So we cannot submit a package that depends on CUDA, since CUDA only supports a few platforms.

**Comment by leedrake5** [comment]
Hi u/hcho3 - that fixed it!!!!! Thank you so much. Is there a reason sudo make install is not included on the Installation Guide? I should have read between the lines, but if this were explicit I wouldn't have missed it. 

I echo your CRAN frustration, but I think it is becoming common for developers to rely on specific gits. Many thanks for all the time you've put into XGBoost.

**Comment by hcho3** [comment]
@leedrake5 It's in this page? https://xgboost.readthedocs.io/en/latest/build.html#installing-r-package-with-gpu-support

**Comment by leedrake5** [comment]
Yes - I see my error. I was working under Building with GPU support, and then just used the -DR_LIB=ON tag. I missed the other portion of the page. Thank you for the clarification.
