### ISSUE TITLE
 /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by /home/marcuschan/Downloads/poc/xgboost/python-package/xgboost/../../lib/libxgboost.so)"

### ISSUE THREAD

**Issue by rajkoder** [dmlc/xgboost#8132]
Hi , we tried compiling the custom build of xgboost for multi GPU using NCCL2 and CUDA on. 

**OS: Pop Os Linux 22.04
gcc version : default is 11.2 
gcc used to build the xgboost : 10
xgboost version : 1.5.2**

### Steps Followed:
clone the xgboost git repo
cd ~/Downloads/poc/xgboost/
mkdir build
cd build
CC=gcc-11.2 CXX=g++-11.2 cmake .. -DUSE_CUDA=ON -DUSE_NCCL=ON -DNCCL_ROOT=/usr/include/nccl.h
make -j4

### Result: 

      Build Failed stating:
      [Parameter packs not expanded with '...'  ArgTypes]

**We tried to build it gcc 10 :** 

cd ~/Downloads/poc/xgboost/
mkdir build
cd build
CC=gcc-10 CXX=g++-10 cmake .. -DUSE_CUDA=ON -DUSE_NCCL=ON -DNCCL_ROOT=/usr/include/nccl.h
make -j4

### Result:

     Build Successful and able to install the package. Now, when we try to run the code in PYCHARM.

     Error: 

       "/usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by 
      /home/marcuschan/Downloads/poc/xgboost/python-package/xgboost/../../lib/libxgboost.so)"]

       I have tried this command and i can see the 3.4.30 version but still somehow xgboost failing to pick 
       
       strings /usr/lib64/libstdc++.so.6 | grep GLIBC
  

Any help is much appreciated.

**Comment by StrikerRUS** [comment]
This looks like the same issue as https://github.com/microsoft/LightGBM/issues/5106.

Please check the following comment for possible workarounds: https://github.com/microsoft/LightGBM/issues/5106#issuecomment-1121925896.

**Comment by Jumabek** [comment]
So I used gcc/g++ version 9 and it worked

![image](https://user-images.githubusercontent.com/4343873/182513476-e2107a75-ecd0-4918-ad67-eaf46dea006d.png)

**Comment by trivialfis** [comment]
Consider using the default gcc.
