### ISSUE TITLE
XGBoost 1.7 multi-instance GPU training with Dask - NCCL error

### ISSUE THREAD

**Issue by dewan-c** [dmlc/xgboost#8929]
Hello, we tried out multi instance GPU training(ex: 2 X g4dn.2xlarge), with Dask, with XGBoost 1.7.4, and we get the following error. But the same training setup works if we use 1.5.2. Is there any change needed in inter node communication to make training work for 1.7? 
We also don't see this issue for objective `reg:squarederror`, but it happens for binary classification tasks.

Hyperparameters used:
```
hyperparams = {
    "objective": "binary:logistic",
    "num_round": "1000",
    "eval_metric": "error",
    "tree_method": "gpu_hist",
    "verbosity": "3",
}
```

We're using SageMaker's container for XGBoost, which starts the cluster with [Dask Cuda workers in each instance](https://github.com/aws/sagemaker-xgboost-container/blob/master/src/sagemaker_xgboost_container/distributed_gpu/dask_cluster_utils.py#L27), and [calls](https://github.com/aws/sagemaker-xgboost-container/blob/master/src/sagemaker_xgboost_container/distributed_gpu/distributed_gpu_training.py#L164) xgboost.dask.train after data load. 
Data load completes and training starts, but after that we immediately see this error. Thanks in advance!

```[18:46:45] task [xgboost.dask-tcp://10.0.103.71:43979]:tcp://10.0.103.71:43979 got new rank 0
[18:46:49] DEBUG: ../src/tree/updater_gpu_hist.cu:751: [GPU Hist]: Configure
[18:46:50] ======== Monitor (0): SketchContainer ========
[18:46:50] WARNING: ../src/common/timer.cc:43: Timer for AllReduce did not get stopped properly.
[18:46:50] WARNING: ../src/common/timer.cc:43: Timer for MakeCuts did not get stopped properly.
[18:46:50] ScanInput: 0.000816s, 1 calls @ 816us
[18:46:50] ======== Monitor (0): ellpack_page ========
[18:46:50] WARNING: ../src/common/timer.cc:43: Timer for Quantiles did not get stopped properly.
[18:46:50] ======== Monitor (1): SketchContainer ========
[18:46:50] WARNING: ../src/common/timer.cc:43: Timer for AllReduce did not get stopped properly.
[18:46:50] WARNING: ../src/common/timer.cc:43: Timer for MakeCuts did not get stopped properly.
[18:46:50] ScanInput: 0.00082s, 1 calls @ 820us
[18:46:50] ======== Monitor (1): ellpack_page ========
[18:46:50] WARNING: ../src/common/timer.cc:43: Timer for Quantiles did not get stopped properly.
2023-03-16 18:46:52,741 - distributed.scheduler - INFO - Remove client Client-c54c72af-c42a-11ed-802f-123388d7d4a0
2023-03-16 18:46:52,751 - distributed.core - INFO - Received 'close-stream' from tcp://10.0.103.71:58544; closing.
2023-03-16 18:46:52,751 - distributed.scheduler - INFO - Remove client Client-c54c72af-c42a-11ed-802f-123388d7d4a0
2023-03-16 18:46:52,752 - distributed.scheduler - INFO - Close client connection: Client-c54c72af-c42a-11ed-802f-123388d7d4a0
Traceback (most recent call last):
  File "/miniconda3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/miniconda3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/opt/ml/code/dask_entry_script_csv.py", line 174, in <module>
    output = xgb.dask.train(client,
  File "/miniconda3/lib/python3.8/site-packages/xgboost/core.py", line 620, in inner_f
    return func(**kwargs)
  File "/miniconda3/lib/python3.8/site-packages/xgboost/dask.py", line 1057, in train
    return client.sync(
  File "/miniconda3/lib/python3.8/site-packages/distributed/utils.py", line 339, in sync
    return sync(
  File "/miniconda3/lib/python3.8/site-packages/distributed/utils.py", line 406, in sync
    raise exc.with_traceback(tb)
  File "/miniconda3/lib/python3.8/site-packages/distributed/utils.py", line 379, in f
    result = yield future
  File "/miniconda3/lib/python3.8/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/miniconda3/lib/python3.8/site-packages/xgboost/dask.py", line 993, in _train_async
    results = await map_worker_partitions(
  File "/miniconda3/lib/python3.8/site-packages/xgboost/dask.py", line 529, in map_worker_partitions
    results = await client.gather(futures)
  File "/miniconda3/lib/python3.8/site-packages/distributed/client.py", line 2154, in _gather
    raise exception.with_traceback(traceback)
  File "/miniconda3/lib/python3.8/site-packages/xgboost/dask.py", line 960, in dispatched_train
    booster = worker_train(
  File "/miniconda3/lib/python3.8/site-packages/xgboost/core.py", line 620, in inner_f
    return func(**kwargs)
  File "/miniconda3/lib/python3.8/site-packages/xgboost/training.py", line 185, in train
    bst.update(dtrain, i, obj)
  File "/miniconda3/lib/python3.8/site-packages/xgboost/core.py", line 1918, in update
    _check_call(_LIB.XGBoosterUpdateOneIter(self.handle,
  File "/miniconda3/lib/python3.8/site-packages/xgboost/core.py", line 279, in _check_call
    raise XGBoostError(py_str(_LIB.XGBGetLastError()))
xgboost.core.XGBoostError: [18:46:50] ../src/tree/updater_gpu_hist.cu:798: Exception in gpu_hist: [18:46:50] ../src/collective/../common/device_helpers.cuh:135: NCCL failure :remote process exited or there was a network error ../src/collective/nccl_device_communicator.cuh(54)
Stack trace:
  [bt] (0) /miniconda3/lib/python3.8/site-packages/xgboost/lib/libxgboost.so(+0x45c64d) [0x7ff0cafa964d]
  [bt] (1) /miniconda3/lib/python3.8/site-packages/xgboost/lib/libxgboost.so(+0x45e3f9) [0x7ff0cafab3f9]
  [bt] (2) /miniconda3/lib/python3.8/site-packages/xgboost/lib/libxgboost.so(+0x4602a6) [0x7ff0cafad2a6]
  [bt] (3) /miniconda3/lib/python3.8/site-packages/xgboost/lib/libxgboost.so(+0x45c9d3) [0x7ff0cafa99d3]
  [bt] (4) /miniconda3/lib/python3.8/site-packages/xgboost/lib/libxgboost.so(+0x4bfb47) [0x7ff0cb00cb47]
  [bt] (5) /miniconda3/lib/python3.8/site-packages/xgboost/lib/libxgboost.so(+0x4c08ce) [0x7ff0cb00d8ce]
  [bt] (6) /miniconda3/lib/python3.8/site-packages/xgboost/lib/libxgboost.so(+0x469e16) [0x7ff0cafb6e16]
  [bt] (7) /miniconda3/lib/python3.8/site-packages/xgboost/lib/libxgboost.so(+0x4e9e68) [0x7ff0cb036e68]
  [bt] (8) /miniconda3/lib/python3.8/site-packages/xgboost/lib/libxgboost.so(+0x4ea6ae) [0x7ff0cb0376ae]
Stack trace:
  [bt] (0) /miniconda3/lib/python3.8/site-packages/xgboost/lib/libxgboost.so(+0x71dd19) [0x7ff0cb26ad19]
  [bt] (1) /miniconda3/lib/python3.8/site-packages/xgboost/lib/libxgboost.so(+0x73d378) [0x7ff0cb28a378]
  [bt] (2) /miniconda3/lib/python3.8/site-packages/xgboost/lib/libxgboost.so(+0x2a0dc9) [0x7ff0cadeddc9]
  [bt] (3) /miniconda3/lib/python3.8/site-packages/xgboost/lib/libxgboost.so(+0x2a1b1d) [0x7ff0cadeeb1d]
  [bt] (4) /miniconda3/lib/python3.8/site-packages/xgboost/lib/libxgboost.so(+0x2dc5f7) [0x7ff0cae295f7]
  [bt] (5) /miniconda3/lib/python3.8/site-packages/xgboost/lib/libxgboost.so(XGBoosterUpdateOneIter+0x70) [0x7ff0cac7abe0]
  [bt] (6) /miniconda3/lib/python3.8/lib-dynload/../../libffi.so.7(+0x69dd) [0x7ff191f5a9dd]
  [bt] (7) /miniconda3/lib/python3.8/lib-dynload/../../libffi.so.7(+0x6067) [0x7ff191f5a067]
  [bt] (8) /miniconda3/lib/python3.8/lib-dynload/_ctypes.cpython-38-x86_64-linux-gnu.so(_ctypes_callproc+0x319) [0x7ff191f731e9]
2023-03-16 18:46:52,822 - distributed.worker - WARNING - Compute Failed
Key:       dispatched_train-13b9cca0-1853-4239-beb0-ee5360cd3dcb
Function:  dispatched_train
args:      ({'verbosity': 3, 'objective': 'binary:logistic', 'tree_method': 'gpu_hist', 'eval_metric': 'error'}, {'DMLC_NUM_WORKER': 2, 'DMLC_TRACKER_URI': '10.0.103.71', 'DMLC_TRACKER_PORT': 46815}, 140630576889760, ['train', 'validation'], [140630576889760, 140630577940320], {'feature_names': None, 'feature_types': None, 'feature_weights': None, 'missing': None, 'enable_categorical': False, 'parts': [{'data':        feature-01  feature-02  feature-03  ...  feature-26  feature-27  feature-28
0        0.869293   -0.635082    0.225690  ...    0.721657    0.988751    0.876678
1        0.907542    0.329147    0.359412  ...    0.779732    0.992356    0.798343
2        0.798835    1.470639   -1.635975  ...    0.803252    0.865924    0.780118
3        1.344385   -0.876626    0.935913  ...    0.869200    1.026736    0.957904
4        1.105009    0.321356    1.522401  ...    1.133295    0.872245    0.808486
...           ...         ...         ...  ...         ...         ...         ...
74635    0.9346
kwargs:    {}
Exception: "XGBoostError('[18:46:50] ../src/tree/updater_gpu_hist.cu:798: Exception in gpu_hist: [18:46:50] ../src/collective/../common/device_helpers.cuh:135: NCCL failure :remote process exited or there was a network error ../src/collective/nccl_device_communicator.cuh(54)\\nStack trace:\\n  [bt] (0) /miniconda3/lib/python3.8/site-packages/xgboost/lib/libxgboost.so(+0x45c64d) [0x7fb652c3a64d]\\n  [bt] (1) /miniconda3/lib/python3.8/site-packages/xgboost/lib/libxgboost.so(+0x45e3f9) [0x7fb652c3c3f9]\\n  [bt] (2) /miniconda3/lib/python3.8/site-packages/xgboost/lib/libxgboost.so(+0x4602a6) [0x7fb652c3e2a6]\\n  [bt] (3) /miniconda3/lib/python3.8/site-packages/xgboost/lib/libxgboost.so(+0x45c9d3) [0x7fb652c3a9d3]\\n  [bt] (4) /miniconda3/lib/python3.8/site-packages/xgboost/lib/libxgboost.so(+0x4bfb47) [0x7fb652c9db47]\\n  [bt] (5) /miniconda3/lib/python3.8/site-packages/xgboost/lib/libxgboost.so(+0x4c08ce) [0x7fb652c9e8ce]\\n  [bt] (6) /miniconda3/lib/python3.8/site-packages/xgboost/lib/libxgboost.so(+0x469e16) [0x7fb652c47e16]\\n  [bt] (7) /miniconda3/lib/python3.8/site-packages/xgboost/lib/libxgboost.so(+0x4e9e68) [0x7fb652cc7e68]\\n  [bt] (8) /miniconda3/lib/python3.8/site-packages/xgboost/lib/libxgboost.so(+0x4ea6ae) [0x7fb652cc86ae]\\n\\n\\n\\nStack trace:\\n  [bt] (0) /miniconda3/lib/python3.8/site-packages/xgboost/lib/libxgboost.so(+0x71dd19) [0x7fb652efbd19]\\n  [bt] (1) /miniconda3/lib/python3.8/site-packages/xgboost/lib/libxgboost.so(+0x73d378) [0x7fb652f1b378]\\n  [bt] (2) /miniconda3/lib/python3.8/site-packages/xgboost/lib/libxgboost.so(+0x2a0dc9) [0x7fb652a7edc9]\\n  [bt] (3) /miniconda3/lib/python3.8/site-packages/xgboost/lib/libxgboost.so(+0x2a1b1d) [0x7fb652a7fb1d]\\n  [bt] (4) /miniconda3/lib/python3.8/site-packages/xgboost/lib/libxgboost.so(+0x2dc5f7) [0x7fb652aba5f7]\\n  [bt] (5) /miniconda3/lib/python3.8/site-packages/xgboost/lib/libxgboost.so(XGBoosterUpdateOneIter+0x70) [0x7fb65290bbe0]\\n  [bt] (6) /miniconda3/lib/python3.8/lib-dynload/../../libffi.so.7(+0x69dd) [0x7fb71dc349dd]\\n  [bt] (7) /miniconda3/lib/python3.8/lib-dynload/../../libffi.so.7(+0x6067) [0x7fb71dc34067]\\n  [bt] (8) /miniconda3/lib/python3.8/lib-dynload/_ctypes.cpython-38-x86_64-linux-gnu.so(_ctypes_callproc+0x319) [0x7fb71dc4d1e9]\\n\\n')"
[2023-03-16:18:46:53:ERROR] ExecuteUserScriptError:
Command "/miniconda3/bin/python3 -m dask_entry_script_csv --eval_metric error --num_round 1000 --objective binary:logistic --tree_method gpu_hist --use_dask_gpu_training True --verbosity 3"
2023-03-16 18:46:52,735 - distributed.worker - WARNING - Compute Failed
Key:       dispatched_train-2b3c1222-a511-42bd-8712-b1fb113b1778
Function:  dispatched_train
args:      ({'verbosity': 3, 'objective': 'binary:logistic', 'tree_method': 'gpu_hist', 'eval_metric': 'error'}, {'DMLC_NUM_WORKER': 2, 'DMLC_TRACKER_URI': '10.0.103.71', 'DMLC_TRACKER_PORT': 46815}, 140630576889760, ['train', 'validation'], [140630576889760, 140630577940320], {'feature_names': None, 'feature_types': None, 'feature_weights': None, 'missing': None, 'enable_categorical': False, 'parts': [{'data':        feature-01  feature-02  feature-03  ...  feature-26  feature-27  feature-28
0        0.705317    0.328173   -0.949611  ...    1.471880    0.931361    0.814569
1        0.555799   -1.505810   -0.000796  ...    0.791748    0.872126    0.772578
2        0.531824    0.360314    1.485226  ...    2.213101    1.279034    1.058182
3        0.935909   -0.261078    1.397557  ...    0.145946    1.016972    0.850355
4        2.040917    0.534655   -1.072791  ...    0.392952    0.766512    0.806905
...           ...         ...         ...  ...         ...         ...         ...
74386    0.5561
kwargs:    {}
Exception: "XGBoostError('[18:46:50] ../src/tree/updater_gpu_hist.cu:798: Exception in gpu_hist: [18:46:50] ../src/collective/../common/device_helpers.cuh:135: NCCL failure :remote process exited or there was a network error ../src/collective/nccl_device_communicator.cuh(54)\\nStack trace:\\n  [bt] (0) /miniconda3/lib/python3.8/site-packages/xgboost/lib/libxgboost.so(+0x45c64d) [0x7ff0cafa964d]\\n  [bt] (1) /miniconda3/lib/python3.8/site-packages/xgboost/lib/libxgboost.so(+0x45e3f9) [0x7ff0cafab3f9]\\n  [bt] (2) /miniconda3/lib/python3.8/site-packages/xgboost/lib/libxgboost.so(+0x4602a6) [0x7ff0cafad2a6]\\n  [bt] (3) /miniconda3/lib/python3.8/site-packages/xgboost/lib/libxgboost.so(+0x45c9d3) [0x7ff0cafa99d3]\\n  [bt] (4) /miniconda3/lib/python3.8/site-packages/xgboost/lib/libxgboost.so(+0x4bfb47) [0x7ff0cb00cb47]\\n  [bt] (5) /miniconda3/lib/python3.8/site-packages/xgboost/lib/libxgboost.so(+0x4c08ce) [0x7ff0cb00d8ce]\\n  [bt] (6) /miniconda3/lib/python3.8/site-packages/xgboost/lib/libxgboost.so(+0x469e16) [0x7ff0cafb6e16]\\n  [bt] (7) /miniconda3/lib/python3.8/site-packages/xgboost/lib/libxgboost.so(+0x4e9e68) [0x7ff0cb036e68]\\n  [bt] (8) /miniconda3/lib/python3.8/site-packages/xgboost/lib/libxgboost.so(+0x4ea6ae) [0x7ff0cb0376ae]\\n\\n\\n\\nStack trace:\\n  [bt] (0) /miniconda3/lib/python3.8/site-packages/xgboost/lib/libxgboost.so(+0x71dd19) [0x7ff0cb26ad19]\\n  [bt] (1) /miniconda3/lib/python3.8/site-packages/xgboost/lib/libxgboost.so(+0x73d378) [0x7ff0cb28a378]\\n  [bt] (2) /miniconda3/lib/python3.8/site-packages/xgboost/lib/libxgboost.so(+0x2a0dc9) [0x7ff0cadeddc9]\\n  [bt] (3) /miniconda3/lib/python3.8/site-packages/xgboost/lib/libxgboost.so(+0x2a1b1d) [0x7ff0cadeeb1d]\\n  [bt] (4) /miniconda3/lib/python3.8/site-packages/xgboost/lib/libxgboost.so(+0x2dc5f7) [0x7ff0cae295f7]\\n  [bt] (5) /miniconda3/lib/python3.8/site-packages/xgboost/lib/libxgboost.so(XGBoosterUpdateOneIter+0x70) [0x7ff0cac7abe0]\\n  [bt] (6) /miniconda3/lib/python3.8/lib-dynload/../../libffi.so.7(+0x69dd) [0x7ff191f5a9dd]\\n  [bt] (7) /miniconda3/lib/python3.8/lib-dynload/../../libffi.so.7(+0x6067) [0x7ff191f5a067]\\n  [bt] (8) /miniconda3/lib/python3.8/lib-dynload/_ctypes.cpython-38-x86_64-linux-gnu.so(_ctypes_callproc+0x319) [0x7ff191f731e9]\\n\\n')"
2023-03-16 18:46:53,033 - distributed.core - INFO - Connection to tcp://10.0.103.71:8786 has been closed.
2023-03-16 18:46:53,033 - distributed.worker - INFO - Stopping worker at tcp://10.0.68.6:40789. Reason: worker-handle-scheduler-connection-broken```

**Comment by dewan-c** [comment]
Thanks @hcho3 ! We also just found [this](https://github.com/dmlc/xgboost/issues/7982) other issue, and tried setting the [NCCL_SOCKET_IFNAME](https://docs.nvidia.com/deeplearning/nccl/user-guide/docs/env.html#nccl-socket-ifname) env variable, and it worked. Should have searched more beforehand, but thanks the info!
