### ISSUE TITLE
'thrust::system::system_error'   what():  for_each: failed to synchronize: cudaErrorIllegalAddress: an illegal memory access was encountered when training XGBoostDaskClassifier

### ISSUE THREAD

**Issue by nshyamkpler** [dmlc/xgboost#8958]
Hi, getting strange error when trying to train a fairly small dataset (130k rows, 72 features) using XGBoost Dask Classifier with a GPU instance. Not sure if this is a dataset issue or not but issue only appears in the 1.7.4 update of XGBoost. When XGBoost is changed to <=1.7.3 this issue does not occur.

Have been trying to narrow the issue down for the last couple days. No changes to span.h that I can see recently and no other packages have changed in our repo apart from xgboost.

We have these following versions installed that pertain to this issue.

``` 
"dask==2023.2.1",
"dask-cuda==23.4.0a230228",
"xgboost==1.7.4" 
```

Further stack trace:

```
../include/xgboost/span.h:540: T &xgboost::common::Span<T, Extent>::operator[](unsigned long) const [with T = const xgboost::FeatureType, Extent = 18446744073709551615UL]: block: [166,0,0], thread: [0,0,0] Assertion `((_idx) < (size()))` failed.
../include/xgboost/span.h:540: T &xgboost::common::Span<T, Extent>::operator[](unsigned long) const [with T = const xgboost::FeatureType, Extent = 18446744073709551615UL]: block: [166,0,0], thread: [1,0,0] Assertion `((_idx) < (size()))` failed.
../include/xgboost/span.h:540: T &xgboost::common::Span<T, Extent>::operator[](unsigned long) const [with T = const xgboost::FeatureType, Extent = 18446744073709551615UL]: block: [166,0,0], thread: [2,0,0] Assertion `((_idx) < (size()))` failed.
../include/xgboost/span.h:540: T &xgboost::common::Span<T, Extent>::operator[](unsigned long) const [with T = const xgboost::FeatureType, Extent = 18446744073709551615UL]: block: [166,0,0], thread: [3,0,0] Assertion `((_idx) < (size()))` failed.
../include/xgboost/span.h:540: T &xgboost::common::Span<T, Extent>::operator[](unsigned long) const [with T = const xgboost::FeatureType, Extent = 18446744073709551615UL]: block: [166,0,0], thread: [4,0,0] Assertion `((_idx) < (size()))` failed.
../include/xgboost/span.h:540: T &xgboost::common::Span<T, Extent>::operator[](unsigned long) const [with T = const xgboost::FeatureType, Extent = 18446744073709551615UL]: block: [166,0,0], thread: [5,0,0] Assertion `((_idx) < (size()))` failed.
../include/xgboost/span.h:540: T &xgboost::common::Span<T, Extent>::operator[](unsigned long) const [with T = const xgboost::FeatureType, Extent = 18446744073709551615UL]: block: [166,0,0], thread: [6,0,0] Assertion `((_idx) < (size()))` failed.
../include/xgboost/span.h:540: T &xgboost::common::Span<T, Extent>::operator[](unsigned long) const [with T = const xgboost::FeatureType, Extent = 18446744073709551615UL]: block: [166,0,0], thread: [7,0,0] Assertion `((_idx) < (size()))` failed.
../include/xgboost/span.h:540: T &xgboost::common::Span<T, Extent>::operator[](unsigned long) const [with T = const xgboost::FeatureType, Extent = 18446744073709551615UL]: block: [166,0,0], thread: [8,0,0] Assertion `((_idx) < (size()))` failed.
../include/xgboost/span.h:540: T &xgboost::common::Span<T, Extent>::operator[](unsigned long) const [with T = const xgboost::FeatureType, Extent = 18446744073709551615UL]: block: [166,0,0], thread: [9,0,0] Assertion `((_idx) < (size()))` failed.
../include/xgboost/span.h:540: T &xgboost::common::Span<T, Extent>::operator[](unsigned long) const [with T = const xgboost::FeatureType, Extent = 18446744073709551615UL]: block: [166,0,0], thread: [10,0,0] Assertion `((_idx) < (size()))` failed.
../include/xgboost/span.h:540: T &xgboost::common::Span<T, Extent>::operator[](unsigned long) const [with T = const xgboost::FeatureType, Extent = 18446744073709551615UL]: block: [166,0,0], thread: [11,0,0] Assertion `((_idx) < (size()))` failed.
```
This goes on for further.

**Comment by trivialfis** [comment]
Could you please share the parameters that you are using, along with the sparsity of the dataset?

**Comment by trivialfis** [comment]
Thank you for sharing, will look into it.

**Comment by trivialfis** [comment]
Could you please use the [nightly build](https://xgboost.readthedocs.io/en/stable/install.html#nightly-build) for now? I think the issue is fixed by https://github.com/dmlc/xgboost/pull/8850 .

**Comment by nshyamkpler** [comment]
@trivialfis Thank you! That seems like the error we are seeing here. Will try the nightly
